### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by akshatnitd** [divyanshumehta/sih18#1]
@divyanshumehta It should contain the Problem Statement, Ministry Name, Problem Code Number, Technology Stack used, Team Members Names, github ids and email Ids (mention the team leader), which is mentioned in the guidelines.

**Comment by ashuray** [comment]
@akshatnitd This is an open repository we cant use terms related to SIH 18 , because it may cause unnecessary access of our code to other college students. Better we put the information regarding the team only .
For problem statement we could use google form for our personal use .

**Comment by akshatnitd** [comment]
@ashuray You can change the README.md after the hackathon or atleast mention the Problem Statement, Tech Stack and Member details. Hope this works
